<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../DevQuestion.Contracts/DevQuestion.Contracts.csproj" />
    <ProjectReference Include="../DevQuestion.Domain/DevQuestion.Domain.csproj" />
    <ProjectReference Include="..\DevQuestion.Application\DevQuestion.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.3.13" />
  </ItemGroup>

</Project>
